### PR TITLE
Update rubies and rails supports

### PR DESCRIPTION
**Pull request by nicolas-brousse**
- Add ruby 3.3 support
- Remove ruby 2.7 support
- Remove Rails 6.0 support
- Fix `sqlite` requirement

### CODE REVIEW

**Comment by nicolas-brousse** [comment]
@Spone Maybe I should also drop support fort old rubies and rails versions. What do you think about?

**Review by Spone — APPROVED** [review]

**Comment by Spone** [comment]
@nicolas-brousse we can drop Rails 6.0, but let's keep 6.1 since [ViewComponent supports it](https://viewcomponent.org/compatibility.html).

**Comment by Spone** [comment]
We can also remove Ruby 2.7 and 3.0 that are [no longer supported](https://endoflife.date/ruby).

**Comment by nicolas-brousse** [comment]
@Spone should we keep test on `view_component` `v2.*` for latest rails versions too?

**Comment by Spone** [comment]
Yes, I think. At least until ViewComponent v4 is released.

**Comment by nicolas-brousse** [comment]
Ok, I've to dig to understand how to fix this https://github.com/pantographe/view_component-form/actions/runs/9914182370/job/27392784399?pr=164#step:4:1174. Seems to be the last thing that block the CI

**Review by Spone — APPROVED** [review]

**Pull request merged**
